
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gui
 */
public class SlotGameGUI extends javax.swing.JFrame {
    private Jogador j;
    private double apostaMontante;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SlotGameGUI.class.getName());
    private Timer slotTimer;
    private int contaCiclo = 0;
    private final int maxCiclo = 30;
    private final String[] RECURSOS = {
            "/recursos/barra.jpg",
            "/recursos/cereja.jpg",
            "/recursos/moeda.jpg",
            "/recursos/sete.jpg"
    };

    /**
     * Creates new form SlotGameGUI
     * @param j
     */
    public SlotGameGUI(Jogador j) {
        initComponents();
        this.j = j;
        this.apostaMontante = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        slot1 = new javax.swing.JLabel();
        slot2 = new javax.swing.JLabel();
        slot3 = new javax.swing.JLabel();
        botaoGirar = new javax.swing.JButton();
        aposta = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        iconBonanza = new javax.swing.JLabel();
        aposta5 = new javax.swing.JButton();
        aposta10 = new javax.swing.JButton();
        aposta25 = new javax.swing.JButton();
        zeraAposta = new javax.swing.JButton();
        allin = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        aposta50 = new javax.swing.JButton();
        aposta100 = new javax.swing.JButton();
        aposta250 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));
        setPreferredSize(new java.awt.Dimension(660, 700));
        setResizable(false);

        slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/barra.jpg"))); // NOI18N
        slot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        slot1.setPreferredSize(new java.awt.Dimension(150, 150));

        slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/barra.jpg"))); // NOI18N
        slot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        slot2.setPreferredSize(new java.awt.Dimension(150, 150));

        slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/barra.jpg"))); // NOI18N
        slot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        slot3.setPreferredSize(new java.awt.Dimension(150, 150));

        botaoGirar.setBackground(new java.awt.Color(255, 204, 51));
        botaoGirar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoGirar.setText("GIRAR");
        botaoGirar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoGirar.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoGirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGirarActionPerformed(evt);
            }
        });

        aposta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aposta.setForeground(new java.awt.Color(204, 0, 0));
        aposta.setText("SUA APOSTA:");
        aposta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        saldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saldo.setForeground(new java.awt.Color(51, 153, 0));
        saldo.setText("SALDO:");
        saldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        iconBonanza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bonanza simbolo.png"))); // NOI18N

        aposta5.setBackground(new java.awt.Color(51, 153, 0));
        aposta5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aposta5.setText("5");
        aposta5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposta5ActionPerformed(evt);
            }
        });

        aposta10.setBackground(new java.awt.Color(51, 153, 0));
        aposta10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aposta10.setText("10");
        aposta10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposta10ActionPerformed(evt);
            }
        });

        aposta25.setBackground(new java.awt.Color(51, 153, 0));
        aposta25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aposta25.setText("25");
        aposta25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposta25ActionPerformed(evt);
            }
        });

        zeraAposta.setBackground(new java.awt.Color(255, 255, 0));
        zeraAposta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        zeraAposta.setText("ZERAR APOSTA");
        zeraAposta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        zeraAposta.setPreferredSize(new java.awt.Dimension(88, 47));
        zeraAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeraApostaActionPerformed(evt);
            }
        });

        allin.setBackground(new java.awt.Color(204, 0, 0));
        allin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        allin.setText("ALL IN");
        allin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allin.setPreferredSize(new java.awt.Dimension(47, 23));
        allin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allinActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultado.setText("RESULTADO: -");
        resultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        aposta50.setBackground(new java.awt.Color(51, 153, 0));
        aposta50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aposta50.setText("50");
        aposta50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposta50ActionPerformed(evt);
            }
        });

        aposta100.setBackground(new java.awt.Color(51, 153, 0));
        aposta100.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aposta100.setText("100");
        aposta100.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposta100ActionPerformed(evt);
            }
        });

        aposta250.setBackground(new java.awt.Color(51, 153, 0));
        aposta250.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aposta250.setText("250");
        aposta250.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aposta250.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposta250ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconBonanza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(resultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aposta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addComponent(saldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoGirar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zeraAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aposta5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aposta50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aposta100, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aposta250, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aposta10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aposta25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconBonanza)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoGirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aposta5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zeraAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aposta10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aposta25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aposta250, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aposta100, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aposta50, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGirarActionPerformed
        this.animacaoDeGiro();
        
        this.saldo.setText("SALDO: " + this.j.getSaldo());
    }//GEN-LAST:event_botaoGirarActionPerformed

    private void aposta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposta5ActionPerformed
       this.apostaMontante += 5;
       this.aposta.setText("APOSTA: " + this.apostaMontante);
       verificaApostaMaxima();
    }//GEN-LAST:event_aposta5ActionPerformed

    private void aposta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposta10ActionPerformed
        this.apostaMontante += 10;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        verificaApostaMaxima();
    }//GEN-LAST:event_aposta10ActionPerformed

    private void aposta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposta25ActionPerformed
        this.apostaMontante += 25;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        verificaApostaMaxima();
    }//GEN-LAST:event_aposta25ActionPerformed

    private void zeraApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeraApostaActionPerformed
        this.apostaMontante = 0;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
    }//GEN-LAST:event_zeraApostaActionPerformed

    private void allinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allinActionPerformed
        this.apostaMontante = this.j.getSaldo();
        this.aposta.setText("APOSTA: " + this.apostaMontante);
    }//GEN-LAST:event_allinActionPerformed

    private void aposta50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposta50ActionPerformed
        this.apostaMontante += 50;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        verificaApostaMaxima();
    }//GEN-LAST:event_aposta50ActionPerformed

    private void aposta100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposta100ActionPerformed
        this.apostaMontante += 100;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        verificaApostaMaxima();
    }//GEN-LAST:event_aposta100ActionPerformed

    private void aposta250ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposta250ActionPerformed
       this.apostaMontante += 250;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        verificaApostaMaxima();
    }//GEN-LAST:event_aposta250ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new SlotGameGUI().setVisible(true));
    }

    private void girar(double aposta){
        // sequencia = array com as figuras dos 3 slots
        int[] sequencia = new int[3];


            sequencia = SlotGame.calcularSequencia();
            //muda os slots para as imagens correspondetes
            switch(sequencia[0]){
                case 1:
                    slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/barra.jpg")));
                    break;
                case 2:
                    slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cereja.jpg")));
                    break;
                case 3:
                    slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/moeda.jpg")));
                    break;
                case 4:
                    slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sete.jpg")));
                    break;
                }
            switch(sequencia[1]){
                case 1:
                    slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/barra.jpg")));
                    break;
                case 2:
                    slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cereja.jpg")));
                    break;
                case 3:
                    slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/moeda.jpg")));
                    break;
                case 4:
                    slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sete.jpg")));
                    break;
                }
            switch(sequencia[2]){
                case 1:
                    slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/barra.jpg")));
                    break;
                case 2:
                    slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cereja.jpg")));
                    break;
                case 3:
                    slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/moeda.jpg")));
                    break;
                case 4:
                    slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sete.jpg")));
                    break;
                }
        
        double ganho = SlotGame.calcularGanho(sequencia);
        this.apostaMontante *= ganho;

        j.setSaldo(j.getSaldo()+apostaMontante);
        this.saldo.setText("SALDO: " + this.j.getSaldo());
        
        //altera a mensagem no resultado de acordo com o ganho.
        if(ganho != 0){
            resultado.setText("RESULTADO: GANHOU!!! " + ganho+"x");
            resultado.setForeground(new java.awt.Color(0, 255, 0));
        }else{
            resultado.setText("RESULTADO: PERDEU... :(");
            resultado.setForeground(new java.awt.Color(255, 0, 0));
        }
        this.apostaMontante = 0;
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        

    }
    
    
    public void configuracaoInicial(){
        this.aposta.setText("APOSTA: " + this.apostaMontante);
        this.saldo.setText("SALDO: " + this.j.getSaldo());
    }
    private void verificaApostaMaxima(){
        if(this.apostaMontante > this.j.getSaldo()){
            this.apostaMontante = this.j.getSaldo();
            this.aposta.setText("APOSTA: " + this.apostaMontante);
        }
    }
    
    private void animacaoDeGiro() {
        if(apostaMontante != 0){
            contaCiclo = 0;

            //desliga botoes
            botaoGirar.setEnabled(false);
            aposta5.setEnabled(false);
            aposta10.setEnabled(false);
            aposta25.setEnabled(false);
            aposta50.setEnabled(false);
            aposta100.setEnabled(false);
            aposta250.setEnabled(false);
            zeraAposta.setEnabled(false);
            allin.setEnabled(false);

            //retira o valor apostado do saldo
            j.setSaldo(j.getSaldo()-this.apostaMontante);

            //gira o slot
            slotTimer = new javax.swing.Timer(80, new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    int rand1 = (int) (Math.random() * 4);
                    int rand2 = (int) (Math.random() * 4);
                    int rand3 = (int) (Math.random() * 4);

                    slot1.setIcon(new javax.swing.ImageIcon(getClass().getResource(RECURSOS[rand1])));
                    slot2.setIcon(new javax.swing.ImageIcon(getClass().getResource(RECURSOS[rand2])));
                    slot3.setIcon(new javax.swing.ImageIcon(getClass().getResource(RECURSOS[rand3])));

                    contaCiclo++;

                    //se acabaram os ciclos para o timer liga os botoes e faz a funçao de aposta;
                    if (contaCiclo >= maxCiclo) {
                        slotTimer.stop(); // Para o Timer

                        // Reabilita os botões
                        botaoGirar.setEnabled(true);
                        aposta5.setEnabled(true);
                        aposta10.setEnabled(true);
                        aposta25.setEnabled(true);
                        aposta50.setEnabled(true);
                        aposta100.setEnabled(true);
                        aposta250.setEnabled(true);
                        zeraAposta.setEnabled(true);
                        allin.setEnabled(true);

                        girar(apostaMontante);
                    }

                }});

            slotTimer.start();
        }else JOptionPane.showMessageDialog(null, "APOSTE UM VALOR MAIOR QUE ZERO!");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allin;
    private javax.swing.JLabel aposta;
    private javax.swing.JButton aposta10;
    private javax.swing.JButton aposta100;
    private javax.swing.JButton aposta25;
    private javax.swing.JButton aposta250;
    private javax.swing.JButton aposta5;
    private javax.swing.JButton aposta50;
    private javax.swing.JButton botaoGirar;
    private javax.swing.JLabel iconBonanza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel slot1;
    private javax.swing.JLabel slot2;
    private javax.swing.JLabel slot3;
    private javax.swing.JButton zeraAposta;
    // End of variables declaration//GEN-END:variables
}